### ISSUE TITLE
Modification request

### ISSUE THREAD

**Issue by nickel110** [ricohapi/awesome-theta#3]
Hi,
Thank you for introducing my repositories in your document.
But, I'm afraid your description of these repositories may mislead about the  status of the  software.
So, could you please add  some description which make clear that these repositories are not created or maintained by your group?
In addition, I hope you could correct the inappropriate comment for the libptp2 as my modification is not specific to the THETA.

**Comment by nickel110** [comment]
What about the gstthetauvc?

**Comment by DaisukeHohjoh** [comment]
https://github.com/ricohapi/awesome-theta/commit/791f46021cf1e26d560102f9357fa3ff53eab70f
Fix the description of `gstthetauvc` as well. Sorry for late our checking.
