### ISSUE TITLE
Request for deletion

### ISSUE THREAD

**Issue by nickel110** [ricohapi/awesome-theta#8]
Please remove my repositories from the list. And from now on, please do not refer my repositories to your customers in any way.

**Comment by DaisukeHohjoh** [comment]
@nickel110 

> Please remove my repositories from the list.
Ricoh removed your repositories from the list.

> And from now on, please do not refer my repositories to your customers in any way.
Okay, I shared your request internally.

Best regards,
Daisuke Hohjoh
